baseURL = "https://www.cs.unm.edu/~jose.castellanosjoo/"
languageCode = "en-us"
title = "Jose Abel Castellanos Joo"
theme = "jose-soho"

[params]
author = "Jose Abel Castellanos Joo"
title = "Jose Abel Castellanos Joo"
description = "Ph.D. student"
images = ["images/my_face_squared_2.png"]
profilePicture = "images/my_face_squared_2.png"

themeColor = "#C10037"

# summarylength = 10
# enableEmoji = true

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
# customJs = ["js/blog.js"]

## Set as many as you want.
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/joseabelcj"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/typesAreSpaces"

[menu]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[markup]

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true # if false, you need to provide you own custom CSS
style = "monokai"
tabWidth = 4
