baseURL = "https://typesarespaces.github.io/"
languageCode = "en-us"
title = "Prof. Deepak Kapur"
theme = "kapur-soho"

[params]
title = "Prof. Deepak Kapur"
images = ["images/deepak-kapurn.jpg"]
profilePicture = "images/deepak-kapurn.jpg"

themeColor = "#C10037"

[menu]
